Item:
  - 6666
  - 8888
Lore:
  - "BanLore1."
  - "BanLore2."
Use:
  - "BANBLOCKTYPE"
####  3 ban tempBan recovery ###
OPPunishment: customPunishment
CreativePunishment: customPunishment
ItemPunishment: recovery
LorePunishment: recovery
UsePunishment: recovery
####
WhiteListOP:
  - OPWhiteList
WhiteListCreative:
  - CreativeWhiteList
ItemWhiteList:
  - ItemWhiteList
LoreWhiteList:
  - LoreWhiteList
UseWhiteList:
  - UseWhiteList
####
PunishmentSwitch:
  OPPunishmentSwitch: true
  CreativePunishmentSwitch: true
  ItemPunishmentSwitch: true
  LorePunishmentSwitch: true
  UsePunishmentSwitch: true
####
CustomPunishment: "ban %player%"
RecoveryMessage: "物品 <item> 被回收."
#Nether door command
NetherCommand: "spawn %player%"
#Ban mobs
BanMobs:
  - "Zombie"
####
LocBanCommands:
  - "worldname:10,10,10:6:spawm:禁止使用 <command> 在这个区域."
LocResBanCommands:
  - "name:spawn:在此区域禁止使用 <command> 这个指令"